// @generated by scripts/generate-cc2-s2-direct-180-kicks.mjs; DO NOT EDIT.
// Source-qualified direct-180 SRS+ offsets for the placement-level native frontier.
// Consumed only by the reviewed, default-disabled direct-180 movegen edge.

pub(crate) const DIRECT_180_GENERATOR_ID: &str = "cc2-s2-direct-180-source-qualified-generator/1";
pub(crate) const DIRECT_180_CONVERSION_VERSION: &str = "cc2-piece-location-origin-delta-y-inversion/1";
pub(crate) const DIRECT_180_TETO_VERSION: &str = "4.2.7";
pub(crate) const DIRECT_180_TETO_RESOLVED: &str = "https://registry.npmjs.org/@haelp/teto/-/teto-4.2.7.tgz";
pub(crate) const DIRECT_180_TETO_INTEGRITY: &str = "sha512-U2fFvh9JKrOXdZD5U28UUgViEk+OlHHpspPrERQrAJf047oSBzT3uaCRJhZXuVxT/EJnvwr2f1k7jYRWoqZ/Gg==";
pub(crate) const DIRECT_180_PACKAGE_JSON_SHA256: &str = "c9a369d0169c2190ee6c561632a353400aa81d239d38920cf5978c5bcd483440";
pub(crate) const DIRECT_180_PACKAGE_LOCK_SHA256: &str = "f696025ad30c23a6d41372a18466685dcafda3622c50225c17afbe20f9ef37bd";
pub(crate) const DIRECT_180_KICK_DATA_SHA256: &str = "6623e02efb05f856cb611464a38c6441bf93f087156599bc7ad3bef21d910e0d";
pub(crate) const DIRECT_180_KICK_INDEX_SHA256: &str = "236d6589358b205d02ae8f58fb404a152739c5d659c0aa044df0415db807ca81";
pub(crate) const DIRECT_180_ADAPTER_ORIGIN_OWNER_SHA256: &str = "b1d8bf945d8f8d9f82913c79ac5818fd270bb960d8bcde7c83f685818d9952df";
pub(crate) const DIRECT_180_SOURCE_FINGERPRINT_SHA256: &str = "7eac4384a718b1e922100d2aa3e7b0dc90a3f0986b915f7b11c1b8271f12bae3";

pub(crate) const DIRECT_180_MAX_ROWS: usize = 6;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct Direct180Row {
    pub(crate) native_offset: (i8, i8),
    pub(crate) source_offset: (i8, i8),
    // None plus initial=true is the unshifted test; None plus initial=false is padding.
    pub(crate) source_row: Option<u8>,
    pub(crate) initial: bool,
    pub(crate) fin_or_tst_override: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct Direct180Transition {
    pub(crate) piece: crate::data::Piece,
    pub(crate) from: crate::data::Rotation,
    pub(crate) to: crate::data::Rotation,
    pub(crate) source_transition: &'static str,
    pub(crate) source_table: &'static str,
    pub(crate) row_count: u8,
    pub(crate) configured_row_count: u8,
    pub(crate) rows: [Direct180Row; DIRECT_180_MAX_ROWS],
}

pub(crate) static DIRECT_180_I_NORTH_TO_SOUTH: [Direct180Row; DIRECT_180_MAX_ROWS] = [
    Direct180Row { native_offset: (1, -1), source_offset: (0, 0), source_row: None, initial: true, fin_or_tst_override: false },
    Direct180Row { native_offset: (1, 0), source_offset: (0, -1), source_row: Some(0), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
];

pub(crate) static DIRECT_180_I_WEST_TO_EAST: [Direct180Row; DIRECT_180_MAX_ROWS] = [
    Direct180Row { native_offset: (1, 1), source_offset: (0, 0), source_row: None, initial: true, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 1), source_offset: (-1, 0), source_row: Some(0), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
];

pub(crate) static DIRECT_180_I_SOUTH_TO_NORTH: [Direct180Row; DIRECT_180_MAX_ROWS] = [
    Direct180Row { native_offset: (-1, 1), source_offset: (0, 0), source_row: None, initial: true, fin_or_tst_override: false },
    Direct180Row { native_offset: (-1, 0), source_offset: (0, 1), source_row: Some(0), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
];

pub(crate) static DIRECT_180_I_EAST_TO_WEST: [Direct180Row; DIRECT_180_MAX_ROWS] = [
    Direct180Row { native_offset: (-1, -1), source_offset: (0, 0), source_row: None, initial: true, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, -1), source_offset: (1, 0), source_row: Some(0), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: false, fin_or_tst_override: false },
];

pub(crate) static DIRECT_180_O_NORTH_TO_SOUTH: [Direct180Row; DIRECT_180_MAX_ROWS] = [
    Direct180Row { native_offset: (1, 1), source_offset: (0, 0), source_row: None, initial: true, fin_or_tst_override: false },
    Direct180Row { native_offset: (1, 2), source_offset: (0, -1), source_row: Some(0), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (2, 2), source_offset: (1, -1), source_row: Some(1), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 2), source_offset: (-1, -1), source_row: Some(2), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (2, 1), source_offset: (1, 0), source_row: Some(3), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 1), source_offset: (-1, 0), source_row: Some(4), initial: false, fin_or_tst_override: false },
];

pub(crate) static DIRECT_180_O_WEST_TO_EAST: [Direct180Row; DIRECT_180_MAX_ROWS] = [
    Direct180Row { native_offset: (-1, 1), source_offset: (0, 0), source_row: None, initial: true, fin_or_tst_override: false },
    Direct180Row { native_offset: (-2, 1), source_offset: (-1, 0), source_row: Some(0), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (-2, 3), source_offset: (-1, -2), source_row: Some(1), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (-2, 2), source_offset: (-1, -1), source_row: Some(2), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (-1, 3), source_offset: (0, -2), source_row: Some(3), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (-1, 2), source_offset: (0, -1), source_row: Some(4), initial: false, fin_or_tst_override: false },
];

pub(crate) static DIRECT_180_O_SOUTH_TO_NORTH: [Direct180Row; DIRECT_180_MAX_ROWS] = [
    Direct180Row { native_offset: (-1, -1), source_offset: (0, 0), source_row: None, initial: true, fin_or_tst_override: false },
    Direct180Row { native_offset: (-1, -2), source_offset: (0, 1), source_row: Some(0), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (-2, -2), source_offset: (-1, 1), source_row: Some(1), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, -2), source_offset: (1, 1), source_row: Some(2), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (-2, -1), source_offset: (-1, 0), source_row: Some(3), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, -1), source_offset: (1, 0), source_row: Some(4), initial: false, fin_or_tst_override: false },
];

pub(crate) static DIRECT_180_O_EAST_TO_WEST: [Direct180Row; DIRECT_180_MAX_ROWS] = [
    Direct180Row { native_offset: (1, -1), source_offset: (0, 0), source_row: None, initial: true, fin_or_tst_override: false },
    Direct180Row { native_offset: (2, -1), source_offset: (1, 0), source_row: Some(0), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (2, 1), source_offset: (1, -2), source_row: Some(1), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (2, 0), source_offset: (1, -1), source_row: Some(2), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (1, 1), source_offset: (0, -2), source_row: Some(3), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (1, 0), source_offset: (0, -1), source_row: Some(4), initial: false, fin_or_tst_override: false },
];

pub(crate) static DIRECT_180_GENERIC_NORTH_TO_SOUTH: [Direct180Row; DIRECT_180_MAX_ROWS] = [
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: true, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 1), source_offset: (0, -1), source_row: Some(0), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (1, 1), source_offset: (1, -1), source_row: Some(1), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (-1, 1), source_offset: (-1, -1), source_row: Some(2), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (1, 0), source_offset: (1, 0), source_row: Some(3), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (-1, 0), source_offset: (-1, 0), source_row: Some(4), initial: false, fin_or_tst_override: false },
];

pub(crate) static DIRECT_180_GENERIC_WEST_TO_EAST: [Direct180Row; DIRECT_180_MAX_ROWS] = [
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: true, fin_or_tst_override: false },
    Direct180Row { native_offset: (-1, 0), source_offset: (-1, 0), source_row: Some(0), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (-1, 2), source_offset: (-1, -2), source_row: Some(1), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (-1, 1), source_offset: (-1, -1), source_row: Some(2), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 2), source_offset: (0, -2), source_row: Some(3), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 1), source_offset: (0, -1), source_row: Some(4), initial: false, fin_or_tst_override: false },
];

pub(crate) static DIRECT_180_GENERIC_SOUTH_TO_NORTH: [Direct180Row; DIRECT_180_MAX_ROWS] = [
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: true, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, -1), source_offset: (0, 1), source_row: Some(0), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (-1, -1), source_offset: (-1, 1), source_row: Some(1), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (1, -1), source_offset: (1, 1), source_row: Some(2), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (-1, 0), source_offset: (-1, 0), source_row: Some(3), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (1, 0), source_offset: (1, 0), source_row: Some(4), initial: false, fin_or_tst_override: false },
];

pub(crate) static DIRECT_180_GENERIC_EAST_TO_WEST: [Direct180Row; DIRECT_180_MAX_ROWS] = [
    Direct180Row { native_offset: (0, 0), source_offset: (0, 0), source_row: None, initial: true, fin_or_tst_override: false },
    Direct180Row { native_offset: (1, 0), source_offset: (1, 0), source_row: Some(0), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (1, 2), source_offset: (1, -2), source_row: Some(1), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (1, 1), source_offset: (1, -1), source_row: Some(2), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 2), source_offset: (0, -2), source_row: Some(3), initial: false, fin_or_tst_override: false },
    Direct180Row { native_offset: (0, 1), source_offset: (0, -1), source_row: Some(4), initial: false, fin_or_tst_override: false },
];

pub(crate) static DIRECT_180_TRANSITIONS: [Direct180Transition; 28] = [
    Direct180Transition { piece: crate::data::Piece::I, from: crate::data::Rotation::North, to: crate::data::Rotation::South, source_transition: "02", source_table: "i_kicks", row_count: 2, configured_row_count: 1, rows: DIRECT_180_I_NORTH_TO_SOUTH },
    Direct180Transition { piece: crate::data::Piece::I, from: crate::data::Rotation::West, to: crate::data::Rotation::East, source_transition: "31", source_table: "i_kicks", row_count: 2, configured_row_count: 1, rows: DIRECT_180_I_WEST_TO_EAST },
    Direct180Transition { piece: crate::data::Piece::I, from: crate::data::Rotation::South, to: crate::data::Rotation::North, source_transition: "20", source_table: "i_kicks", row_count: 2, configured_row_count: 1, rows: DIRECT_180_I_SOUTH_TO_NORTH },
    Direct180Transition { piece: crate::data::Piece::I, from: crate::data::Rotation::East, to: crate::data::Rotation::West, source_transition: "13", source_table: "i_kicks", row_count: 2, configured_row_count: 1, rows: DIRECT_180_I_EAST_TO_WEST },
    Direct180Transition { piece: crate::data::Piece::O, from: crate::data::Rotation::North, to: crate::data::Rotation::South, source_transition: "02", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_O_NORTH_TO_SOUTH },
    Direct180Transition { piece: crate::data::Piece::O, from: crate::data::Rotation::West, to: crate::data::Rotation::East, source_transition: "31", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_O_WEST_TO_EAST },
    Direct180Transition { piece: crate::data::Piece::O, from: crate::data::Rotation::South, to: crate::data::Rotation::North, source_transition: "20", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_O_SOUTH_TO_NORTH },
    Direct180Transition { piece: crate::data::Piece::O, from: crate::data::Rotation::East, to: crate::data::Rotation::West, source_transition: "13", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_O_EAST_TO_WEST },
    Direct180Transition { piece: crate::data::Piece::T, from: crate::data::Rotation::North, to: crate::data::Rotation::South, source_transition: "02", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_NORTH_TO_SOUTH },
    Direct180Transition { piece: crate::data::Piece::T, from: crate::data::Rotation::West, to: crate::data::Rotation::East, source_transition: "31", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_WEST_TO_EAST },
    Direct180Transition { piece: crate::data::Piece::T, from: crate::data::Rotation::South, to: crate::data::Rotation::North, source_transition: "20", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_SOUTH_TO_NORTH },
    Direct180Transition { piece: crate::data::Piece::T, from: crate::data::Rotation::East, to: crate::data::Rotation::West, source_transition: "13", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_EAST_TO_WEST },
    Direct180Transition { piece: crate::data::Piece::L, from: crate::data::Rotation::North, to: crate::data::Rotation::South, source_transition: "02", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_NORTH_TO_SOUTH },
    Direct180Transition { piece: crate::data::Piece::L, from: crate::data::Rotation::West, to: crate::data::Rotation::East, source_transition: "31", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_WEST_TO_EAST },
    Direct180Transition { piece: crate::data::Piece::L, from: crate::data::Rotation::South, to: crate::data::Rotation::North, source_transition: "20", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_SOUTH_TO_NORTH },
    Direct180Transition { piece: crate::data::Piece::L, from: crate::data::Rotation::East, to: crate::data::Rotation::West, source_transition: "13", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_EAST_TO_WEST },
    Direct180Transition { piece: crate::data::Piece::J, from: crate::data::Rotation::North, to: crate::data::Rotation::South, source_transition: "02", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_NORTH_TO_SOUTH },
    Direct180Transition { piece: crate::data::Piece::J, from: crate::data::Rotation::West, to: crate::data::Rotation::East, source_transition: "31", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_WEST_TO_EAST },
    Direct180Transition { piece: crate::data::Piece::J, from: crate::data::Rotation::South, to: crate::data::Rotation::North, source_transition: "20", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_SOUTH_TO_NORTH },
    Direct180Transition { piece: crate::data::Piece::J, from: crate::data::Rotation::East, to: crate::data::Rotation::West, source_transition: "13", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_EAST_TO_WEST },
    Direct180Transition { piece: crate::data::Piece::S, from: crate::data::Rotation::North, to: crate::data::Rotation::South, source_transition: "02", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_NORTH_TO_SOUTH },
    Direct180Transition { piece: crate::data::Piece::S, from: crate::data::Rotation::West, to: crate::data::Rotation::East, source_transition: "31", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_WEST_TO_EAST },
    Direct180Transition { piece: crate::data::Piece::S, from: crate::data::Rotation::South, to: crate::data::Rotation::North, source_transition: "20", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_SOUTH_TO_NORTH },
    Direct180Transition { piece: crate::data::Piece::S, from: crate::data::Rotation::East, to: crate::data::Rotation::West, source_transition: "13", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_EAST_TO_WEST },
    Direct180Transition { piece: crate::data::Piece::Z, from: crate::data::Rotation::North, to: crate::data::Rotation::South, source_transition: "02", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_NORTH_TO_SOUTH },
    Direct180Transition { piece: crate::data::Piece::Z, from: crate::data::Rotation::West, to: crate::data::Rotation::East, source_transition: "31", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_WEST_TO_EAST },
    Direct180Transition { piece: crate::data::Piece::Z, from: crate::data::Rotation::South, to: crate::data::Rotation::North, source_transition: "20", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_SOUTH_TO_NORTH },
    Direct180Transition { piece: crate::data::Piece::Z, from: crate::data::Rotation::East, to: crate::data::Rotation::West, source_transition: "13", source_table: "kicks", row_count: 6, configured_row_count: 5, rows: DIRECT_180_GENERIC_EAST_TO_WEST },
];

pub(crate) fn direct_180_transition(piece: crate::data::Piece, from: crate::data::Rotation) -> &'static Direct180Transition {
    DIRECT_180_TRANSITIONS.iter().find(|entry| entry.piece == piece && entry.from == from)
        .expect("generated direct-180 table must cover every piece and rotation")
}
